social_comment_upload.settings:
  type: config_object
  label: 'Social Comment Upload Settings'
  mapping:
    allow_upload_comments:
      type: boolean
      label: 'Allow file uploads in comments'
