name: Improved Theme Settings
type: module
description: Makes the theme pages a bit UI friendly for people with the permissions.
core_version_requirement: ^9
package: Custom

# Information added by Drupal.org packaging script on 2023-09-18
version: '11.10.1+0-dev'
project: 'social'
datestamp: 1695039258
